/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.Formatacao;
import apoio.ValidarGabriel;
import dao.ClientesDAO;
import entidade.Clientes;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel.ferreira1
 */
public class IfrClientes extends javax.swing.JInternalFrame {

    int codigo = 0;

    /**
     * Creates new form IfrClientes
     */
    public IfrClientes() {
        initComponents();
        Formatacao.formatarCpf(tfdCPF);
        Formatacao.formatarTelefone(tfdTelefone);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfdSituacao = new javax.swing.JTextField();
        tfdCPF = new javax.swing.JFormattedTextField();
        tfdRG = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfdEmail = new javax.swing.JTextField();
        tfdTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        tfdCriterioPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setTitle("Cadastro de Clientes");

        jLabel1.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel2.setText("RG:");

        jLabel5.setText("CPF:");

        jLabel6.setText("Situação:");

        tfdCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCPFActionPerformed(evt);
            }
        });
        tfdCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfdCPFKeyReleased(evt);
            }
        });

        jLabel9.setText("Telefone (fixo):");

        jLabel10.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfdRG, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdEmail)))
                                .addGap(2, 2, 2))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tfdCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfdSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jLabel4.setText("Critério");

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Search-32.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfdCriterioPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdCriterioPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Delete-32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(115, 57));
        btnExcluir.setMinimumSize(new java.awt.Dimension(115, 57));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Application-32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setMaximumSize(new java.awt.Dimension(115, 57));
        btnEditar.setMinimumSize(new java.awt.Dimension(115, 57));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Select-48.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ball-standby-48.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setMaximumSize(new java.awt.Dimension(115, 57));
        btnFechar.setMinimumSize(new java.awt.Dimension(115, 57));
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(27, 27, 27)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new ClientesDAO().popularTabela(tblClientes, tfdCriterioPesquisa.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String idString = String.valueOf(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        String retorno = new ClientesDAO().excluir(id);

        if (retorno == null) {
            JOptionPane.showMessageDialog(null, "Registro inativado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Problemas ao inativar registro.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String idString = String.valueOf(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Clientes c = new ClientesDAO().consultarId(id);

        if (c == null) {
            JOptionPane.showMessageDialog(null, "Registro não localizado!");
        } else {
            codigo = c.getCliente_id();

            // mudar a aba ativa para Cadastro
            jTabbedPane1.setSelectedIndex(0);

            // coloca dados nos campos de interface
            tfdNome.setText(c.getNome());
            tfdRG.setText(c.getRg());
            tfdCPF.setText(c.getCpf());
            tfdTelefone.setText(c.getTelefone());
            tfdEmail.setText(c.getEmail());
            tfdSituacao.setText(String.valueOf(c.getSituacao()));
            tfdEndereco.setText(c.getEndereco());

            tfdNome.requestFocus();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Clientes clientinho = new Clientes();

        clientinho.setCliente_id(codigo);
        
        if (tfdNome.getText().equals("")) {
                tfdNome.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo nome do cliente é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setNome(tfdNome.getText());
            }

            if (tfdRG.getText().equals("")) {
                tfdRG.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo RG é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setRg(tfdRG.getText());
            }

            if (tfdCPF.getText().equals("")) {
                tfdCPF.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo CPF é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setCpf(tfdCPF.getText());
            }

            if (tfdTelefone.getText().equals("")) {
                tfdTelefone.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo telefone é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {      
                clientinho.setTelefone(tfdTelefone.getText());
            }

            if (tfdEmail.getText().equals("")) {
                tfdEmail.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo email é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setEmail(tfdEmail.getText());
            }

            if (tfdSituacao.getText().equals("")) {
                tfdSituacao.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo situação é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setSituacao(tfdSituacao.getText().charAt(0));
            }

            if (tfdEndereco.getText().equals("")) {
                tfdEndereco.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo endereço é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setEndereco(tfdEndereco.getText());
            }
        //clientinho.setNome(tfdNome.getText());
        //clientinho.setRg(tfdRG.getText());
        //clientinho.setCpf(tfdCPF.getText());
        //clientinho.setTelefone(tfdTelefone.getText());
        //clientinho.setEmail(tfdEmail.getText());
        //clientinho.setSituacao(tfdSituacao.getText().charAt(0));
        //clientinho.setEndereco(tfdEndereco.getText());

        ClientesDAO clientesDAO = new ClientesDAO();

        //if (ValidarGabriel.validarCPF(tfdCPF.getText())) {
        //    JOptionPane.showMessageDialog(null, "CPF válido.");
        //} else {
        //    JOptionPane.showMessageDialog(null, "CPF inválido.");
        //    tfdCPF.setBackground(Color.yellow);
        //} 
        String retorno = null;

        if (codigo == 0) {
            // salvar = inserir
            if (tfdNome.getText().equals("")) {
                tfdNome.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo nome do cliente é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setNome(tfdNome.getText());
            }

            if (tfdRG.getText().equals("")) {
                tfdRG.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo RG é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setRg(tfdRG.getText());
            }

            if (tfdCPF.getText().equals("")) {
                tfdCPF.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo CPF é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setCpf(tfdCPF.getText());
            }

            if (tfdTelefone.getText().equals("")) {
                tfdTelefone.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo telefone é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {      
                clientinho.setTelefone(tfdTelefone.getText());
            }

            if (tfdEmail.getText().equals("")) {
                tfdEmail.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo email é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setEmail(tfdEmail.getText());
            }

            if (tfdSituacao.getText().equals("")) {
                tfdSituacao.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo situação é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setSituacao(tfdSituacao.getText().charAt(0));
            }

            if (tfdEndereco.getText().equals("")) {
                tfdEndereco.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo endereço é obrigatório, favor preencher.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                clientinho.setEndereco(tfdEndereco.getText());
            }

            retorno = clientesDAO.salvar(clientinho);
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso.");
        } else {
            // atualizar = update
            retorno = clientesDAO.atualizar(clientinho);
            JOptionPane.showMessageDialog(null, "Registro salvo com sucesso.");
        }

        //if (ValidarGabriel.validarCPF(tfdCPF.getText()) && (retorno == null)) {
        if (retorno == null) {
            //JOptionPane.showMessageDialog(null, "CPF válido.");
            //  JOptionPane.showMessageDialog(null, "Registro salvo com sucesso!");

            // limpar campos
            tfdNome.setText("");
            tfdRG.setText("");
            tfdCPF.setText("");
            tfdTelefone.setText("");
            tfdEmail.setText("");
            tfdSituacao.setText("");
            tfdEndereco.setText("");

            // posiciona cursor
            tfdNome.requestFocus();

        } else {
            JOptionPane.showMessageDialog(null, "Ops! Problemas ao salvar registro.");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tfdCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdCPFKeyReleased

    }//GEN-LAST:event_tfdCPFKeyReleased

    private void tfdCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCPFActionPerformed

    }//GEN-LAST:event_tfdCPFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField tfdCPF;
    private javax.swing.JTextField tfdCriterioPesquisa;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JFormattedTextField tfdRG;
    private javax.swing.JTextField tfdSituacao;
    private javax.swing.JFormattedTextField tfdTelefone;
    // End of variables declaration//GEN-END:variables

}
